const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="awabteto@hotmail.com"
global.location="cairo,Egypt."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://awabteto:awabteto@cluster0.texhd9n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://chat.whatsapp.com/ER5t8uFzUcj4OmAWCcJlbM";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029VaZn6N059PwNW717Ww3Q";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029VaZn6N059PwNW717Ww3Q" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/7361e8822f4c4d1737132.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "249124701614" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "249124702614";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "249124702614";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "https://telegra.ph/file/39f7fe63a65c2f412d941.jpg" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "recording" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "true"
global.readmessage = process.env.READ_MESSAGE || "true"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,249xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "249224702614";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_15_23_05_05_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAyMjUsXG4gICAgICAgIDUyLFxuICAgICAgICAxODksXG4gICAgICAgIDMwLFxuICAgICAgICAxMjEsXG4gICAgICAgIDcwLFxuICAgICAgICAyNDksXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjU0LFxuICAgICAgICAzNixcbiAgICAgICAgNzUsXG4gICAgICAgIDg5LFxuICAgICAgICA1MCxcbiAgICAgICAgMTExLFxuICAgICAgICAyMDYsXG4gICAgICAgIDIwNSxcbiAgICAgICAgNjEsXG4gICAgICAgIDk4LFxuICAgICAgICAxNjMsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNjksXG4gICAgICAgIDIxLFxuICAgICAgICA4NSxcbiAgICAgICAgMTg2LFxuICAgICAgICAyMjQsXG4gICAgICAgIDIyMCxcbiAgICAgICAgNzcsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTksXG4gICAgICAgIDExM1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxODYsXG4gICAgICAgIDU4LFxuICAgICAgICAyNDcsXG4gICAgICAgIDQ2LFxuICAgICAgICAxODYsXG4gICAgICAgIDI0MSxcbiAgICAgICAgMzQsXG4gICAgICAgIDMsXG4gICAgICAgIDM2LFxuICAgICAgICAyMjcsXG4gICAgICAgIDQwLFxuICAgICAgICAxMjYsXG4gICAgICAgIDc5LFxuICAgICAgICAxNDUsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjU0LFxuICAgICAgICAyMDEsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMTU4LFxuICAgICAgICA0MCxcbiAgICAgICAgNzUsXG4gICAgICAgIDE1NSxcbiAgICAgICAgMzAsXG4gICAgICAgIDUyLFxuICAgICAgICAyNTQsXG4gICAgICAgIDc1LFxuICAgICAgICA4OCxcbiAgICAgICAgMTg2LFxuICAgICAgICAxMSxcbiAgICAgICAgMTksXG4gICAgICAgIDcyLFxuICAgICAgICA4NVxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODAsXG4gICAgICAgIDE4MSxcbiAgICAgICAgODEsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTI1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMDQsXG4gICAgICAgIDE3MixcbiAgICAgICAgODksXG4gICAgICAgIDY5LFxuICAgICAgICAxNTYsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTY2LFxuICAgICAgICAyMTQsXG4gICAgICAgIDUsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTExLFxuICAgICAgICA1MCxcbiAgICAgICAgMzEsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTA1LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgMTczLFxuICAgICAgICA3MCxcbiAgICAgICAgMTE2LFxuICAgICAgICA3NixcbiAgICAgICAgMjUwLFxuICAgICAgICAxNzEsXG4gICAgICAgIDcwLFxuICAgICAgICAxMjdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTk5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMzUsXG4gICAgICAgIDc4LFxuICAgICAgICAyMDIsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMjIyLFxuICAgICAgICAxMzMsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNTUsXG4gICAgICAgIDkwLFxuICAgICAgICAxNTEsXG4gICAgICAgIDQzLFxuICAgICAgICAyMCxcbiAgICAgICAgMTYsXG4gICAgICAgIDE2LFxuICAgICAgICAxMDcsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjE1LFxuICAgICAgICAxMTksXG4gICAgICAgIDE0NSxcbiAgICAgICAgMTQzLFxuICAgICAgICA2NCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMzgsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTcwLFxuICAgICAgICA4MlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDEwNixcbiAgICAgICAgNzgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgOSxcbiAgICAgICAgMTQ4LFxuICAgICAgICA4OSxcbiAgICAgICAgMTU2LFxuICAgICAgICAyNDUsXG4gICAgICAgIDE2MyxcbiAgICAgICAgNjAsXG4gICAgICAgIDE2NCxcbiAgICAgICAgOTYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTA5LFxuICAgICAgICA4LFxuICAgICAgICAxMTAsXG4gICAgICAgIDg4LFxuICAgICAgICAyNTMsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMjA2LFxuICAgICAgICAxNTcsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTA3LFxuICAgICAgICAyNDMsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTA1LFxuICAgICAgICAyMTgsXG4gICAgICAgIDE1NyxcbiAgICAgICAgMjM0LFxuICAgICAgICAyNDksXG4gICAgICAgIDg3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIyOCxcbiAgICAgICAgNjAsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMTEsXG4gICAgICAgIDc0LFxuICAgICAgICAxMDcsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTU1LFxuICAgICAgICAxODEsXG4gICAgICAgIDk2LFxuICAgICAgICAxODIsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTg4LFxuICAgICAgICAyMDUsXG4gICAgICAgIDk2LFxuICAgICAgICAxNTUsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTg4LFxuICAgICAgICAxODYsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjMzLFxuICAgICAgICAzOCxcbiAgICAgICAgMTQxLFxuICAgICAgICAyMSxcbiAgICAgICAgOTQsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMTg4LFxuICAgICAgICAyNTAsXG4gICAgICAgIDY5LFxuICAgICAgICA5NyxcbiAgICAgICAgNTVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDE0NixcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTAsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMjQxLFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA1MSxcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgNzksXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDIwNSxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTQyLFxuICAgICAgICAgIDc0XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE2NixcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgMTEzLFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICA3MixcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDMsXG4gICAgICAgICAgNDUsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgODEsXG4gICAgICAgICAgNDksXG4gICAgICAgICAgMTQxLFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMCxcbiAgICAgICAgICA1NixcbiAgICAgICAgICA0OCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDc4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQsXG4gICAgICAgIDExNixcbiAgICAgICAgNTUsXG4gICAgICAgIDQsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMzIsXG4gICAgICAgIDI0MCxcbiAgICAgICAgNjgsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMTY3LFxuICAgICAgICA0MixcbiAgICAgICAgODUsXG4gICAgICAgIDk5LFxuICAgICAgICAyMzIsXG4gICAgICAgIDE0MixcbiAgICAgICAgNDQsXG4gICAgICAgIDEzNCxcbiAgICAgICAgMjUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTMxLFxuICAgICAgICAxMzYsXG4gICAgICAgIDgyLFxuICAgICAgICA5OCxcbiAgICAgICAgMjA1LFxuICAgICAgICA0MSxcbiAgICAgICAgMjI1LFxuICAgICAgICA4NSxcbiAgICAgICAgMTk1LFxuICAgICAgICAxNTQsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjEyLFxuICAgICAgICAyNDAsXG4gICAgICAgIDIwLFxuICAgICAgICA5LFxuICAgICAgICAyMzgsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMjAwLFxuICAgICAgICA2NSxcbiAgICAgICAgMjMxLFxuICAgICAgICAxODAsXG4gICAgICAgIDQ3LFxuICAgICAgICA2MixcbiAgICAgICAgOTYsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNTEsXG4gICAgICAgIDExNixcbiAgICAgICAgNDEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMixcbiAgICAgICAgMTUxLFxuICAgICAgICA1OCxcbiAgICAgICAgNDIsXG4gICAgICAgIDQyLFxuICAgICAgICA3NCxcbiAgICAgICAgMjEwLFxuICAgICAgICAyMTMsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMTkwLFxuICAgICAgICAzMSxcbiAgICAgICAgMjMzLFxuICAgICAgICAyNSxcbiAgICAgICAgNDMsXG4gICAgICAgIDcxLFxuICAgICAgICA3XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyMDUsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwic01wbHBodWo2d2dGR3dEcjkwelBJNVlBRUdyNkhUNGJzNnFMZmVlUDR1Yz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5Njc3MTc1NjU3NDhAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjgyQzc3MThERDA2QUZCQTYyNDlDMDFGMzJBNDhBMDlFXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkyMjU5NlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk2NzcxNzU2NTc0OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMEYyNThBMkQ3QUM3MzU2ODRGOTk0ODM2MjRCQjE5NDhcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE0OTIyNTk3XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTY3NzE3NTY1NzQ4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI1QzZGMjY4Q0VCNzk0OTk1RkUyMzU3OUYxOEFERjA4RVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTQ5MjI1OThcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5Njc3MTc1NjU3NDhAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjJBQjJGNUFGNDE5REFGMTUyRUI4NTBFOUM3M0RBMTc4XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDkyMjU5OFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogNjEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogNjEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCIwY1A0X1AtTlQwNnBhMlhCOTNqZy13XCIsXG4gIFwicGhvbmVJZFwiOiBcIjA0ZjA5Y2IzLTJmYjYtNDljZS04YjJlLWU1YTliZTkzMDVmNlwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzEsXG4gICAgICAyNTIsXG4gICAgICA1NCxcbiAgICAgIDE3NCxcbiAgICAgIDU4LFxuICAgICAgMTg4LFxuICAgICAgMTYwLFxuICAgICAgMTgwLFxuICAgICAgMjI2LFxuICAgICAgOTUsXG4gICAgICA4MSxcbiAgICAgIDEwNSxcbiAgICAgIDIwMixcbiAgICAgIDU1LFxuICAgICAgMTAzLFxuICAgICAgNixcbiAgICAgIDcxLFxuICAgICAgNzgsXG4gICAgICAwLFxuICAgICAgMjU1XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE2MSxcbiAgICAgIDk0LFxuICAgICAgODIsXG4gICAgICA4NyxcbiAgICAgIDE5OCxcbiAgICAgIDExMCxcbiAgICAgIDExNixcbiAgICAgIDEwMixcbiAgICAgIDEsXG4gICAgICAxOSxcbiAgICAgIDEzMCxcbiAgICAgIDEzMyxcbiAgICAgIDU3LFxuICAgICAgMTIzLFxuICAgICAgMjEwLFxuICAgICAgMjIsXG4gICAgICAxOTQsXG4gICAgICAxODYsXG4gICAgICAyMzQsXG4gICAgICAyM1xuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCIxRTVQWkY0RFwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTY3NzE3NTY1NzQ4OjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjExMjAzODkzNjM2NzMzMDoxQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcItio2YjYqiDYs9mG2KrYsdin2YRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNLakd6c1FGRU9ISTNyRUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcImRVWmFuUlpmb2Q4dmlBd0FhcllpZ3pzVFlCQzc3a2ZoRkFpQklOZmFkU2c9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiWThGdmpnd2x1OTZObmNXblkwMEw0dk4vWGFJcklDOERNZVkxRVMzamxtQ2EyZGZHdFZhZFpCWUZVSW1PaGlzZU9nT1c4UUk3VFdIUjlDcmViUDNKQWc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiWWxVclVTUXB6bUtHTXpyTiszMkkzdmZCL2R1NzNwaDE5K3g2dklsYUJJZHNsdXVLY2RHQU9zZllUWDhWN245THdOZVhxL3doSDl0S293Q1QrRUxWQWc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTY3NzE3NTY1NzQ4OjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgOTAsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgNDcsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDEyLFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxMzEsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMTksXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA3MSxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxMTcsXG4gICAgICAgICAgNDBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcxNDkyMjU5NixcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQURrTVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRGtNLmpzb24iOiAie1wia2V5RGF0YVwiOlwidnlwbmhqa0plY2tUTUp6Qk9acDNuOGpFbGtYUDlCWS95V3UyN3pteTg4cz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNDg2MDcwNTY4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTQ5MjI1OTY1MjFcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "A17_Md", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || "all",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.4",
  caption : process.env.CAPTION || "بوت عمكم تيتو" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "bot teto🇸🇩",
  packname: process.env.PACK_NAME || "awabofficial",
  botname : process.env.BOT_NAME  || "تيتـو عمكم",
  ownername:process.env.OWNER_NAME|| "It'x A-teto",


  errorChat : process.env.ERROR_CHAT || "false",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "28a488511643f099af3ee201ead77e70";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
